services:
  jmeter-master:
    image: justb4/jmeter:5.5
    container_name: jmeter-performance-test
    volumes:
      - ./test-plans:/test-plans
      - ./results:/results
      - ./config:/config
    command: 
      - -n
      - -t
      - /test-plans/api-performance.jmx
      - -l
      - /results/results.jtl
      - -e
      - -o
      - /results/html-report
      - -Jthreads=5
      - -Jrampup=10
      - -Jduration=30