services:
  jmeter-performance-test:
    image: justb4/jmeter:5.5
    container_name: jmeter-performance-test
    volumes:
      - ./test-plans:/test-plans
      - ./results:/results
    command: [
      "-n",
      "-t", "/test-plans/api-performance.jmx",
      "-l", "/results/results.jtl",
      "-Jthreads=50",
      "-Jrampup=120",
      "-Jduration=300",
      "-f",
      "-e",
      "-o", "/results/html-report"
    ]